export const categoryKeywords = {
  Emissions: "Emissions",
  Employment: "Employment Indicators",
  Environment: "Environmental Data",
  Food: "Food Data",
  Exchange: "Exchange Rate Data",
  Forestry: "Forestry",
  Inputs: "Input Data",
  Investment: "Investment Data",
  "Macro-Statistics": "Macro-Statistics",
  Population: "Population Data",
  Prices: "Price Data",
  Production: "Production Data",
  SDG_BulkDownloads: "SDG Bulk Downloads",
  SUA: "SUA Crops Livestock",
};
